### ISSUE TITLE
tile mode

### ISSUE THREAD

**Issue by meetar** [tangrams/render-tests#13]
allow specifying a particular tile to draw, rather than by latlong

**Comment by nvkelso** [comment]
This would be great – we already specify specific tiles per features in the
vector-datasource tests, might allow those to be reused / adapted.

On Wed, Apr 13, 2016 at 12:25 PM, Peter Richardson <notifications@github.com

**Comment by meetar** [comment]
resolved with https://github.com/tangrams/differ/commit/32333561ba8d87f4ddaba8a2cb6fd1562bfd2843
