### ISSUE TITLE
Provide user feedback when library fails with 401 auth error

### ISSUE THREAD

**Issue by bcamper** [tangrams/render-tests#31]
We should provide user feedback when the library fails to load due to a 401 auth error -- such as when a precog link is provided but the user isn't authorized.

(There are other http responses we should probably handle as well, but starting here since it's a known issue.)

**Comment by meetar** [comment]
In the precog case, if the user isn't authorized, the result isn't a 401 error – it's the "authorize github" page. Any ideas about how to work with this? Or is precog also throwing a 401 somewhere that I could catch? / @migurski

**Comment by migurski** [comment]
I believe the "authorize" page is also status=401, or it could be if that were useful.
