### ISSUE TITLE
can't load zipped styles

### ISSUE THREAD

**Issue by meetar** [tangrams/render-tests#54]
Loading: https://tangrams.github.io/differ/?1=https://mapzen.com/carto/tron-style-more-labels/2/tron-style-more-labels.zip&2=https://mapzen.com/carto/tron-style-more-labels/2/tron-style-more-labels.zip&lib1=https://mapzen.com/tangram/0.9/tangram.debug.js&lib2=0.10&go

Fails with:
```
Starting Diff
Unexpected filetype: tron-style-more-labels.zip
Unexpected filetype: tron-style-more-labels.zip
File load failed.
Stopping Diff.
```

**Comment by nvkelso** [comment]
If you need quick access to diffing Tron, the tron-style-more-labels.yaml
file on the same endpoint does include all required files (unlike the
github src).

**Comment by meetar** [comment]
Yep, that's not a problem at all, this issue is strictly about the .zip functionality. Thanks!

**Comment by meetar** [comment]
Fixed with https://github.com/tangrams/differ/commit/6d34724025d8ee0ecb6e4068e7f950df5d947092
